name: Tests (Linux)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    name: Python ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Create html dir
        run: mkdir -p html
      - name: Check pip
        run: pip --version
      - name: Update pip
        run: pip install --upgrade pip
      - name: Install pipenv
        run: pip install pipenv
      - name: pipenv install
        run: pipenv --bare install --dev
      - name: Integration tests
        run: make integration-tests
      - name: Config environment variables tests
        run: make env-test
      - name: Unit tests
        run: make unit-test
      - name: Network logger tests
        run: make network-test
      - name: Upload to codecov
        run: pipenv run codecov --token="${{ secrets.CODECOV_TOKEN }}"
      - uses: codecov/codecov-action@v1
